Started porting terminal functionality over

diff --git a/.bash/aliases b/.bash/aliases
--- a/.bash/aliases
+++ b/.bash/aliases
@@ -1,14 +1,59 @@
-# Make an alias for invoking commands you use constantly
-# File system
-if command -v eza &>/dev/null; then
-  alias ls='eza --group-directories-first --icons=auto'
-  alias l='eza -lhF --group-directories-first --icons=auto'
-  alias la='eza -lahF --group-directories-first --icons=auto'
+# INFO: Aliases
+if exists eza; then
+alias ls='eza --group-directories-first --icons=auto'
+alias l='eza -lhF --group-directories-first --icons=auto'
+alias la='eza -lahF --group-directories-first --icons=auto'
+fi
+
+
+if exists zoxide; then
+alias cd="zd"
+zd() {
+  if (( $# == 0 )); then
+    builtin cd ~ || return
+      elif [[ -d $1 ]]; then
+      builtin cd "$1" || return
+  else
+    if ! z "$@"; then
+      echo "Error: Directory not found"
+        return 1
+        fi
+
+        printf "\U000F17A9 "
+        pwd
+        fi
+}
 fi
 
 alias grep='grep --color=auto'
+
+if exists fzf; then
 alias ffe="fzf --preview 'bat --style=numbers --color=always {}' -e"
+
+if [[ "$TERM" == "xterm-kitty" ]]; then
+alias ff="fzf --preview 'case \$(file --mime-type -b {}) in image/*) kitty icat --clear --transfer-mode=memory --stdin=no --place=\${FZF_PREVIEW_COLUMNS}x\${FZF_PREVIEW_LINES}@0x0 {} ;; *) bat --style=numbers --color=always {} ;; esac'"
+else
+alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
+fi
+alias ffe="fzf --preview 'bat --style=numbers --color=always {}' -e"
+alias eff='$EDITOR "$(ff)"'
+sff() {
+  if [ $# -eq 0 ]; then
+    echo "Usage: sff <destination> (e.g. sff host:/tmp/)"
+      return 1
+      fi
+      local file
+      file=$(find . -type f -printf '%T@\t%p\n' | sort -rn | cut -f2- | ff) && [ -n "$file" ] && scp "$file" "$1"
+}
+fi
+if exists fastfetch; then
 alias cf='cd && clear && fastfetch'
+fi
+if exists tmux; then
 alias tnew='tmux new -A -s $("$HOME/.config/hypr/scripts/cap_term_name")'
+fi
+if exists git && exists lazygit; then
 alias dots='git --git-dir=$HOME/.dots.git/ --work-tree=$HOME'
 alias lazydots='lazygit --git-dir=$HOME/.dots.git/ --work-tree=$HOME'
+fi
+
